### PR TITLE
Release Candidate 3.2.0

### PR DESCRIPTION
**Pull request by dsifford**
**New Features**

- Citations are now sorted automatically based on how sorting is defined in the citation style (no more drag and drop).
- In-text citations styles now reflect each individual citation style.
- Improvements to the UI.
- Realtime citation style switching.
- "Full note" style citations are now fully supported. (eg. Chicago Full Note).

**Bugfixes**

- Fix bug that caused some options to not be saved on the options page.
- Fix issue that caused the plugin to break if your site is SSL encrypted.
- Fix bug related to conference proceedings fields. HT @metallikat36
- Reference list now enabled for all post types. HT @halatkins

**Depreciations**

- If you have custom CSS, check your selectors. I've made some changes to selector names (the largest of which is using dashes `-` rather than underscores `_`).
- The last-occurring ordered list is not tagged as a bibliography on page load anymore. This is now done upon initial bibliography creation. You shouldn't notice a difference, but some users who have used this plugin for a longer period of time may find that some of their older bibliographys are not being correctly identified. Email me if this is an issue and I'll walk you thorough it.

### CODE REVIEW

**Comment by metallikat36** [comment]
Hi Derek,

Could you help me with this update. I updated the plugin and it actually did not change the appearance of my inline citations (meaning the custom CSS was still being applied even though I had underscores everywhere rather than dashes). I also noted at this point the tooltips where not appearing.

Then I changed my custom CSS to have dashes everywhere, and that actually made my inline citations plain, as if there is no custom CSS:
http://www.earthmedresearch.org/neuropathy-natural-medicine/

Also, the collapsable References heading to the bibliography is now gone.  

Can you help me adapt my old posts to this update?

Here is my custom CSS if it helps:

```
.abt-cite {   
vertical-align: super;   
font-size: 11px; 
color: #ea6900;
}

.abt-tooltip{
color: white !important;
background: black !important;
border: solid 2px;
border-color: #ea6900;
z-index: 10000002;
}

.abt-arrow-up { 
  border-color: transparent transparent black !important; 
z-index: 10000001;
} 

.abt-arrow-down { 
  border-color: black transparent transparent !important; 
z-index: 10000001;
}

.abt-tooltip-touch-close{
z-index: 10000002;
}

#abt-smart-bib-toggle, #abt-smart-bib-container h3 {
   font-size: 22px; 
}

#abt-smart-bib-toggle.abt-hidden.noselect::before, #abt-smart-bib-toggle.noselect::before {
margin-left: 10px;
}
```

**Comment by dsifford** [comment]
Hm... didn't really think of the fact that old posts would have the css selectors ingrained.. Let me work on a quick fix.

**Comment by dsifford** [comment]
@metallikat36 Keep the new selectors as-is (you'll need them)...

In order for everything to be seamless, you'll need to also add back in the old selectors.

I'm adding a fix to the js that is selector agnostic. Will push that out in a bit

**Comment by metallikat36** [comment]
Do you mean I should have stuff like the following throughout?:

.abt-tooltip, .abt_tooltip{
code goes here...
}

**Comment by dsifford** [comment]
Actually nevermind -- "Good form" for css selectors is not better than having an application that works without having to tinker

I'm gonna roll back to the old style.

**Comment by dsifford** [comment]
Gonna build and publish a fix now... Let me know if I missed anything

**Comment by dsifford** [comment]
@metallikat36 Just pushed out the update. Keep me posted. Sorry about that

**Comment by metallikat36** [comment]
Does it take some time for the update to show up on my wordpress dashboard?

**Comment by dsifford** [comment]
Yeah -- it was taking a while for me as well.. I forced the update (we use wp-cli on our server so I can do it from my terminal)

If you don't have that luxury, generally it'll show up within about an hour. 

If that's too long, I can send you a zip

**Comment by dsifford** [comment]
Alternatively, you can grab the zip from here: https://wordpress.org/plugins/academic-bloggers-toolkit/

**Comment by metallikat36** [comment]
1. On the backend, you need to change .abt-tooltip to read .abt_tooltip.

2. You might want to mention on the back end .abt_arrow_down and .abt_arrow_up.

3. The blibliography heading is still missing since the update.

**Comment by dsifford** [comment]
What is going on with your bibliography heading exactly? Can you give me a deeper explanation?

**Comment by metallikat36** [comment]
See this article
http://www.earthmedresearch.org/neuropathy-natural-medicine/
The references are listed, but there is no heading. If it matters, here is the custom CSS on the heading

```
#abt-smart-bib-toggle, #abt-smart-bib-container h3 {
   font-size: 22px; 
}

#abt-smart-bib-toggle.abt-hidden.noselect::before, #abt-smart-bib-toggle.noselect::before {
margin-left: 10px;
}
```

**Comment by dsifford** [comment]
Actually, now I know why... In the past, the headings were added on the fly which I think is much more fragile of a solution than tossing them into the actual post content.

I'm going to keep it as-is, because this is really the better way of doing it....

To fix your issue, just add the following css to your stylesheet...

```css
ol#abt-smart-bib:before {
    content: "Bibliography";
    top: -10px;
    position: relative;
    font-weight: bold;
}

ol#abt-smart-bib {
    padding-top: 10px;
}
```

Example: http://codepen.io/dsifford/pen/zBYVGX

Sorry for the trouble

**Comment by dsifford** [comment]
If you had toggle enabled, here's an alternative solution in javascript that keeps that intact....

```js

(function() {
    
    document.addEventListener('DOMContentLoaded', toggleOldBibs);
    
    function toggleOldBibs() {
        var bib = document.querySelector('ol#abt-smart-bib');
        if (bib) {
            var container = document.createElement('DIV');
            document.body.insertBefore(container, bib)
            var heading = document.createElement('H3');
            heading.innerHTML = 'Bibliography';
            heading.style.cursor = 'pointer';
            container.appendChild(heading);
            container.appendChild(bib);
            heading.addEventListener('click', function(e) {
                e.preventDefault();
                var items = document.querySelectorAll('ol#abt-smart-bib>li');
                var style = 'none'
                if (items[0].style.display === 'none') style = '';
                
                for (var i = 0; i < items.length; i++) {
                    items[i].style.display = style;
                };
                
            });
        }
    }
    
})();
```

example: http://codepen.io/dsifford/pen/beGPpa?editors=1011

**Comment by metallikat36** [comment]
I am able to achieve the look I want with this code:

```
ol#abt-smart-bib:before {
    content: "References";
    left: -10px;
    position: relative;
    font-size: 22px;
}
```

But, yes, the toggle is not showing. The code you gave me - where would I put that? Can you just build that into the plugin? Otherwise I will have to add that code to the plugin everytime there is an update. If faced with that prospect, I would rather just redo my references from scratch on the articles I have already written.

**Comment by metallikat36** [comment]
Also, I tried just now adding a reference to an old article, and the loading wheel just spins forever.

**Comment by metallikat36** [comment]
Made a new test article:
http://www.earthmedresearch.org/abt-plugin-test/

-The toggle does not work
- the inline citations do not reflect my custom CSS
- I have no ability to order the citations the way I want. I used AMA style. The way I added the citations is the way it is, with no apparent way to alter it.

**Comment by metallikat36** [comment]
Ability to modify the references (i.e add, subtract, and reorder) of old posts prior to the update is a must for me.

**Comment by dsifford** [comment]
@metallikat36 

The toggle works for me on the test post that you shared.

> I have no ability to order the citations the way I want. I used AMA style. The way I added the citations is the way it is, with no apparent way to alter it.

This is by design. Many citation styles specify how the citations are to be ordered. I assume that you are interested in ordering by citation occurrence? If so, American Medical Association will do that for you. Just keep inserting citations and new bibliographies and inline citations will be generated each time automatically. 

If you're looking to go alphabetical, there are multiple styles that offer that as well.

> would also want to know how to change the font size and left margin on this bibliography header.

```css
#abt-smart-bib>h3 {
    font-size: 1em;
    margin-left: 10px;
}
```

**Comment by dsifford** [comment]
Re: Editing old citations. Unfortunately, I don't think that's something that I'll be able to build in. I had to completely rewrite the parser to allow for inline citation parsing. 

I'll take a look and see, but, unfortunately, I don't think you'll be able to go back to an older post and modify citations (because at that point in time, there was no cache stored in the post that the processor can use to rebuild itself)

**Comment by dsifford** [comment]
If you totally hate the new version and just want to go back to the old one, you can download it from the wordpress plugin page. I won't be able to offer any technical support for older versions though.

**Comment by metallikat36** [comment]
I got the look I want on the new post with:
```
#abt-smart-bib>h3 {
    font-size: 22px;
    left: 10px;
    position: relative;
}
```

- But  toggle still does not work. I tried clearing all the cache and opening in a private browser. Still didn't work. 
- If I understand correctly, the citations I put in this test article, should appear in ascending order of 1, 2, 3, 4. Currently, when I see the article, I see 1, 4, 2, then 3. It is not in order. Is it in order on your screen?
- custom CSS also still not showing. I see tiny orange superscripts. 
image

If the new features get to work, I am okay with redoing my citations from scratch since I only have 2 articles. Other users might be frustrated though.

**Comment by dsifford** [comment]
> But toggle still does not work

Very strange. It works from my computer (chrome).

image

image


Open your JS console and paste over any error messages (F12 opens the console).

> If I understand correctly, the citations I put in this test article, should appear in ascending order of 1, 2, 3, 4. Currently, when I see the article, I see 1, 4, 2, then 3. It is not in order. Is it in order on your screen?

Yes, that is correct. That is strange that it isn't working that way on your end. I have no idea what could be causing that other than cache. 

Can you open up the test post and enter a few citations and then copy over the console from there as well?

**Comment by metallikat36** [comment]
Also, the field where you can enter a title for the bibliography (such as "References") does not seem to actually do anything.

Which makes me wonder, how did this new post know to title the heading as "References" to begin with if it did not get that information from that field? One possibility is that the custom CSS you gave me to title the older posts is also applying to new posts. (ol#abt-smart-bib:before {
    content: "References";})  But I tried changing that, it did not effect the titles of the headings in the new post. Perhaps another possibility is that the older version of the plugin is in some sense not completely uninstalled.?

I also just noticed that if I reload the page, the very first second the toggle arrow appears, it is pointing downwards (i.e. the expanded position). The very next second, it changes to be horizontal (i.e. the collapsed position), but the list did not collapse along with it.

**Comment by dsifford** [comment]
Sounds like this is definitely a cache issue... Let me see if I can dig in your site's resources and see if I can confirm

**Comment by metallikat36** [comment]
image

**Comment by metallikat36** [comment]
image

**Comment by dsifford** [comment]
I can't seem to reproduce the errors you're getting on my computer. I've tried in firefox and chrome and it works for both. 

There are only two possibilities here: 

1. You have stale resources stuck in your browser's cache.
2. You're using a really old version of Chrome

**Comment by metallikat36** [comment]
Oh snap. I have Windows Vista, I recently got some message about Chrome not supporting vista anymore.  Let me try and get someone else computer and try.

**Comment by metallikat36** [comment]
Okay, now this is interesting. I added references 5, 6, and 7 to that post. They appeared in order 7, 5, then 6. The plugin did not reorder them.  BUT, the plugin this time around decided to reorder 1 through 4.

To recap, if the plugin was entirely broken, I would see 1, 4, 2, 3, 7, 5, 6.
If the plugin was working perfectly, I would see 1, 2, 3, 4, 5, 6, 7
What I am actually seeing is: 1, 2, 3, 4, 7, 5, 6.

**Comment by metallikat36** [comment]
I have chrome Version 49.0.2623.112 m

**Comment by dsifford** [comment]
Standby for a screen recording for what you should actually be seeing.

**Comment by dsifford** [comment]
https://vid.me/7LSZ

**Comment by metallikat36** [comment]
image
 You can see in this screen shot things are not in the right order.

But as I keep adding more references, it comes to be in the right order:
image

The trend that I notice is that if I add citations in a single line like this:

asdfjasdf[3]jsakdflkajskdljkf[2] 

then it messes up. 

But if i have line breaks like:

asdfasdf[1]

asdfasdfasdf[2]

It seems to work.

**Comment by metallikat36** [comment]
image
My caching plugin is currently deactivated and my CLoudFlare is in development mode. Only then did I make this new post. The citations still don't reflect the CSS properly, and toggling still now showing. I also tried viewing in my moms laptop with up-to-date chrome, and it looks no different for me.

**Comment by fbennett** [comment]
@metallikat36: Have all of your tests been on the same version of Chrome? (Seems like reproducing the issue will be key.)

**Comment by metallikat36** [comment]
Everything I have posted is on my Vista machine with that version of Chrome I posted. The only thing I did elsewhere was view the article once on someone elses newer chrome.

**Comment by fbennett** [comment]
Did you edit on the other system, or only view?

**Comment by metallikat36** [comment]
Actually, I can change the font size and color of the inline citations with the custom CSS. The strange thing is that the selector is applying differently to my articles post-update versus pre-update. So like I made the font size of the inline citations larger, but in doing so, it makes the font of my older articles may larger than I want. This is okay, since the plan is to delete the citations of my old articles and redo them anyway, but it may give insight into what's wrong.

**Comment by metallikat36** [comment]
only view

**Comment by metallikat36** [comment]
anyone else confirm the plugin works for them yet?

**Comment by dsifford** [comment]
I'm able to reproduce the backtrack-same-line issue... I'll push a fix for that tomorrow. If I continue forward and add citations on the same line, there is no issue. It's only backtracking on the same line.

All other issues, I can't reproduce. Your bibliography is toggling here on my machine.

Just noticed you joined the discussion @fbennett! Any ideas?

**Comment by fbennett** [comment]
I am able to run Derek's development instance locally, I think. I'll see if it's possible to setyself up with an earlier version of Chrome. If I can break things, it may help pin things down.

**Comment by dsifford** [comment]
Awesome! Let me know if you're able to turn something up 👍 

PS: FYI @metallikat36 --- @fbennett is the mastermind who wrote the [16,000-line citation processor](https://github.com/Juris-M/citeproc-js) that I leverage in this plugin. If anybody can isolate what's going on here, it's him!

notworthy

**Comment by fbennett** [comment]
Oh, stop. :-)

**Comment by metallikat36** [comment]
Now the toggling works on my moms laptop all of a sudden. I don't think I had any cache going on but I would have been wrong. Or maybe it is in someway related to the fact that I got the inline ordering correct by avoiding back-tracking on same line. Or that could just be coincidence.

**Comment by dsifford** [comment]
@metallikat36 Not sure. 

Bed time here for me. I'll pick this back up in the morning. I'm pretty certain that fixing the same line issue will be easy.

Feel free to add any more info to this discussion and I'll browse it in the morning. 👍 

@fbennett If you can't get it running, let me know. You might have better luck by completely destroying the folder and re-pulling. I had to update `typings` to a newer version which could create some issues if you still have old typings installed in the `typings` directory.

Until tomorrow!

**Comment by metallikat36** [comment]
Okay.

I am unable to reproduce the toggle bug on my mom's machine with up-to-date chrome. I can only reproduce it on my vista machine with slightly out of date chrome Version 49.0.2623.112 m.  (Chrome stopped making updates for vista recently)

**Comment by fbennett** [comment]
That's good to know. 49.0.2623.112 does claim to be the Stable Channel release, though, so things should work there as well. I'll see what I can break this afternoon.

**Comment by metallikat36** [comment]
There is however a bug I can reproduce. Changing the field that lets you name the heading of the bibliography doesn't change my heading name. I tested this on up-to-date chrome in a private browsing window, with all my cache turned off. That being the case, I have no idea where it is getting the info to title by bibliographies as "References".

**Comment by dsifford** [comment]
@metallikat36 Unlike before, the headings are set permanently during the creation of your post.

If you change the heading name on the options page and then check to see if the headings of previously published posts change, they will not.

Is that what you are referring to, or will new headings not generate while editing a new post? (you'll have to change the style of the bibliography or add a citation for it to take effect)

**Comment by dsifford** [comment]
@metallikat36 @fbennett I fixed the same line issue.. It was a matter of replacing a single tinymce method with one of my own. Easy fix.

Gonna push out that update here in a few.

**Comment by metallikat36** [comment]
The bug still seems to be present for me after the update:
http://www.earthmedresearch.org/final-test/

As for the headings not changing, I am referring to new posts. Yes, I see that if I change the citations style then the heading gets updated. So no problem. Though FYI, it does not update if I add a citation.

**Comment by dsifford** [comment]
> The bug still seems to be present for me after the update

Can you tell me exactly the steps you take for this to happen so I can replicate?

> Though FYI, it does not update if I add a citation.

Bibliography headings are only re-generated when the processor requires to be created from scratch. There are three things that cause that to happen.

1. Creating a brand new post.
2. Changing your citation style.
3. Opening a saved post(*)

(*) This will not cause the heading to be _applied_ to the post until some action is taken in the post itself. That's because when you open a saved post, all the info that the post needs exists within the editor already. No writes happen until you add a **new** citation, append cite an existing reference somewhere in the document that requires the bibliography numbers to be changed, remove a citation, or change the citation style.

**Comment by metallikat36** [comment]
To reproduce:

-make a new post. 
-Type the letter "a" five times.
-add PMID 123456 at the end of the line
-add PMID 123456 at the start of the line.

You get this:
http://www.earthmedresearch.org/bug-test/

**Comment by dsifford** [comment]
Can't reproduce

https://vid.me/Sjf8

**Comment by metallikat36** [comment]
I can't reproduce it now either. Though I am 100% I updated the plugin before making that new post where they came out in the wrong order. Weird.

**Comment by dsifford** [comment]
Sounds good. 

I appreciate you taking the time to help work out the bugs. Thanks for being so patient!

Keep me posted if something else turns up.

**Comment by metallikat36** [comment]
And thank you for spending all day yesterday chasing a toggle bug that didn't even exist!

**Comment by metallikat36** [comment]
Is there a way I can export references from an old article prior to the update, so that I can import it and use it to make a new version of the article post-update?

**Comment by dsifford** [comment]
Unfortunately not yet. Systems are in place to be able to export from the new version onward though (still not fully finished).

Sorry for the inconvenience.

**Comment by metallikat36** [comment]
FYI, a couple observations about Google Chrome:

On my Vista machine with out of date Chrome, the toolips do not appear. But strangely, if I manually CSS change the font size of the superscript, the tooltips start working. The default size appears to be 16px. So if I make it say either 15px or 17px, the tooltips start displaying. But strangely, if I manually input 16px (i.e. the same same as the default size), the tooltips don't display. Weird. 

On another computer that has Windows 7 and had a slightly newer Chrome than my PC (version 50.something), the reference list toggle was also broken. Then I updated the Chrome on that PC and the toggle then worked. So it's definitely Chrome.

Just FYI's. Nothing really to do here.

**Comment by dsifford** [comment]
very strange.. 

Yeah, not sure how I'd even go about fixing something like that. It's tough when things aren't reproducible.

**Pull request merged**
